application: martindevans
version: 4
runtime: python
api_version: 1

handlers:
- url: /blog/feed.*
  script: blog/feed.py

- url: /blog.*
  script: blog/service.py

- url: /messageboard.*
  script: forumService.py
  login: required

- url: /admin.*
  script: adminPanel.py
  login: admin

- url: /file.*
  script: blobManager.py

- url: /repository.*
  script: repository.py
  login: required

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /javascript
  static_dir: javascript

- url: /pages
  static_dir: pages

- url: /resume
  script: resume.py
  
- url: /restricted
  static_dir: restricted
  login: admin

- url: /cron/messageboard.*
  script: forumService.py
  login: admin

- url: /favicon.ico
  static_dir: images/favicon.ico

- url: /robots.txt
  static_dir: robots.txt

- url: /.*
  script: serviceSelect.py